### PR TITLE
Updated the dependencies

### LINKED ISSUE #4: Fails on 4.0.0
I'm using node 4.0.0:

``` sh
$ node
> require("screenres")
{ set: [Function], get: [Function] }
> require("screenres").get()
node: symbol lookup error: /home/ionicabizau/.../node_modules/screenres/build/Release/screenres.node: undefined symbol: _Z8fetchResv
```

### PR DESCRIPTION
**Pull request by IonicaBizau**
~~A first try to fix #4–not a real fix, but this upgrades the dependencies versions and it's still working on v0.12.6. :grin:~~

Actually it's fixing #4. I ported the C++ file too. :smile:

### CODE REVIEW

**Comment by IonicaBizau** [comment]
@davidmarkclements Can you please take a look here?

**Comment by davidmarkclements** [comment]
@ionicabizau Dude you're awesome - so sorry for inattention I'm going to have to split up my firehose of github notifications to get better visibility - I will check this out in the next 30mins merge and publish as long as no conflicts

**Comment by davidmarkclements** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by IonicaBizau** [comment]
@davidmarkclements Oh, nice! :star:

**Comment by davidmarkclements** [comment]
this is what I'm getting in 0.12.17 when attempting to get or set

```
dyld: lazy symbol binding failed: Symbol not found: _CGMainDisplayID
  Referenced from: /Users/davidclements/z/nearForm/screenres/build/Release/screenres.node
  Expected in: dynamic lookup

dyld: Symbol not found: _CGMainDisplayID
  Referenced from: /Users/davidclements/z/nearForm/screenres/build/Release/screenres.node
  Expected in: dynamic lookup

Trace/BPT trap: 5

```

**Comment by davidmarkclements** [comment]
and when attempting to build on 4.1.2 I get

```
  CXX(target) Release/obj.target/screenres/linux.o
  CXX(target) Release/obj.target/screenres/osx.o
../osx.cc:29:16: error: type 'CGFloat' (aka 'double') cannot be narrowed to
      'int' in initializer list [-Wc++11-narrowing]
      .width = screenSize.width,
               ^~~~~~~~~~~~~~~~
../osx.cc:29:16: note: override this message by inserting an explicit cast
      .width = screenSize.width,
               ^~~~~~~~~~~~~~~~
               static_cast<int>( )
../osx.cc:30:17: error: type 'CGFloat' (aka 'double') cannot be narrowed to
      'int' in initializer list [-Wc++11-narrowing]
      .height = screenSize.height
                ^~~~~~~~~~~~~~~~~
../osx.cc:30:17: note: override this message by inserting an explicit cast
      .height = screenSize.height
                ^~~~~~~~~~~~~~~~~
                static_cast<int>()
```

**Comment by davidmarkclements** [comment]
what version of OS X are you running?

**Comment by IonicaBizau** [comment]
@davidmarkclements Hmm, it compiles successfully on these versions for me (I'm using `nvm`). I am using Ubuntu 15.10.

**Comment by davidmarkclements** [comment]
oh I see you're using the linux bindings

ok so it's broken on OS X but for other reasons. 

ok.. best thing to do here I think is to make this a branch for now till we have OS X covered

then we can publish with next dist tag

```
npm i screenres@next
```

So I don't keep blocking you I've made you a collab on both gh and npm

**Comment by davidmarkclements** [comment]
done

```
npm i screenres@next
```

for node 0.12.x and node 4.x.x support on Linux - OS X todo

**Comment by IonicaBizau** [comment]
@davidmarkclements Thanks for adding me collaborator here! :smile: I was using my fork, so it's not really a blocking thing:

``` json
{
     "screenres": "IonicaBizauKitchen/screenres#updated-dependencies"
}
```

But having this `next` tag is handy too.
